#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiromu Kiyokawa
# SPDX-License-Identifier: BSD-3-clause

import sys

e, o = 0, 0

for b in sys.stdin:
    a = b.strip()
    x = int(a)
    if(int(a) % 2 == 0):
        print(a,"is even number")
        e += x
    elif(int(a) % 2 == 1):
        print(a,"is odd number")
        o += x
    else:
        print("Please enter integer")

print("The sum of even numbers is ", e) 
print("The sum of odd numbers is ", o)
