#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Hiromu Kiyokawa hirosan315911@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

x = random.randint(0, 10)

for i in range(3):
    print("整数をを入力してね " )
    n = input()
    if x < int(n):
        print("その数値は入力された数値より小さいよ")
    elif x > int(n):
        print("その数値は入力された数値より大きいよ")
    elif x == int(n):
        print("おめでとう！その数値は入力された数値だよ！")
    else:
        print("数値を入れてね！")
